apiVersion: riot.vrutkovs.eu/v1alpha1
kind: Riot
metadata:
  name: example-riot
spec:
  replicas: 1
  image: "docker.io/vectorim/riot-web:v1.6.0"
  serverName: "matrix.apps.vrutkovs.devcluster.openshift.com"
  config: |
    {
      "default_server_config": {
          "m.homeserver": {
              "base_url": "https://matrix.apps.vrutkovs.devcluster.openshift.com",
              "server_name": "matrix.apps.vrutkovs.devcluster.openshift.com"
          },
          "m.identity_server": {
              "base_url": "https://matrix.apps.vrutkovs.devcluster.openshift.com"
          }
      },
      "disable_identity_server": true,
      "disable_custom_urls": false,
      "disable_guests": true,
      "disable_login_language_selector": false,
      "disable_3pid_login": false,
      "brand": "Riot",
      "integrations_ui_url": "https://scalar.vector.im/",
      "integrations_rest_url": "https://scalar.vector.im/api",
      "integrations_jitsi_widget_url": "https://scalar.vector.im/api/widgets/jitsi.html",
      "bug_report_endpoint_url": "https://riot.im/bugreports/submit",
      "defaultCountryCode": "GB",
      "showLabsSettings": true,
      "features": {
          "feature_pinning": "labs",
          "feature_custom_status": "labs",
          "feature_custom_tags": "labs",
          "feature_state_counters": "labs",
          "feature_many_integration_managers": "labs",
          "feature_mjolnir": "labs",
          "feature_dm_verification": "labs",
          "feature_cross_signing": "labs"
      },
      "default_federate": true,
      "welcomePageUrl": "home.html",
      "default_theme": "light",
      "roomDirectory": {
          "servers": [
              "matrix.apps.vrutkovs.devcluster.openshift.com",
              "matrix.org"
          ]
      },
      "piwik": {
          "url": "https://piwik.riot.im/",
          "whitelistedHSUrls": ["https://matrix.org"],
          "whitelistedISUrls": ["https://vector.im", "https://matrix.org"],
          "siteId": 1
      },
      "enable_presence_by_hs_url": {
          "https://matrix.org": false
      }
    }
