apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: synapseworkers.synapse.vrutkovs.eu
spec:
  group: synapse.vrutkovs.eu
  names:
    kind: SynapseWorker
    listKind: SynapseWorkerList
    plural: synapseworkers
    singular: synapseworker
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SynapseWorker is the Schema for the synapseworkers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SynapseWorkerSpec defines the desired state of SynapseWorker
          properties:
            port:
              type: integer
            protocol:
              type: string
            replicas:
              type: integer
            resources:
              items:
                description: SynapseWorkerResource defines synapse worker
                properties:
                  names:
                    items:
                      type: string
                    type: array
                required:
                - names
                type: object
              type: array
            synapse:
              type: string
            worker:
              type: string
          required:
          - port
          - protocol
          - replicas
          - resources
          - synapse
          - worker
          type: object
        status:
          description: SynapseWorkerStatus defines the observed state of SynapseWorker
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
