// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Synapse) DeepCopyInto(out *Synapse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Synapse.
func (in *Synapse) DeepCopy() *Synapse {
	if in == nil {
		return nil
	}
	out := new(Synapse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Synapse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseConfig) DeepCopyInto(out *SynapseConfig) {
	*out = *in
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]SynapseVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseConfig.
func (in *SynapseConfig) DeepCopy() *SynapseConfig {
	if in == nil {
		return nil
	}
	out := new(SynapseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseList) DeepCopyInto(out *SynapseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Synapse, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseList.
func (in *SynapseList) DeepCopy() *SynapseList {
	if in == nil {
		return nil
	}
	out := new(SynapseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SynapseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapsePorts) DeepCopyInto(out *SynapsePorts) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapsePorts.
func (in *SynapsePorts) DeepCopy() *SynapsePorts {
	if in == nil {
		return nil
	}
	out := new(SynapsePorts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseSecrets) DeepCopyInto(out *SynapseSecrets) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseSecrets.
func (in *SynapseSecrets) DeepCopy() *SynapseSecrets {
	if in == nil {
		return nil
	}
	out := new(SynapseSecrets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseSpec) DeepCopyInto(out *SynapseSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	out.Secrets = in.Secrets
	out.Ports = in.Ports
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseSpec.
func (in *SynapseSpec) DeepCopy() *SynapseSpec {
	if in == nil {
		return nil
	}
	out := new(SynapseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseStatus) DeepCopyInto(out *SynapseStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseStatus.
func (in *SynapseStatus) DeepCopy() *SynapseStatus {
	if in == nil {
		return nil
	}
	out := new(SynapseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseVolume) DeepCopyInto(out *SynapseVolume) {
	*out = *in
	in.Volume.DeepCopyInto(&out.Volume)
	in.Mount.DeepCopyInto(&out.Mount)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseVolume.
func (in *SynapseVolume) DeepCopy() *SynapseVolume {
	if in == nil {
		return nil
	}
	out := new(SynapseVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseWorker) DeepCopyInto(out *SynapseWorker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseWorker.
func (in *SynapseWorker) DeepCopy() *SynapseWorker {
	if in == nil {
		return nil
	}
	out := new(SynapseWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SynapseWorker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseWorkerConfig) DeepCopyInto(out *SynapseWorkerConfig) {
	*out = *in
	if in.Listeners != nil {
		in, out := &in.Listeners, &out.Listeners
		*out = make([]SynapseWorkerListener, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseWorkerConfig.
func (in *SynapseWorkerConfig) DeepCopy() *SynapseWorkerConfig {
	if in == nil {
		return nil
	}
	out := new(SynapseWorkerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseWorkerList) DeepCopyInto(out *SynapseWorkerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SynapseWorker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseWorkerList.
func (in *SynapseWorkerList) DeepCopy() *SynapseWorkerList {
	if in == nil {
		return nil
	}
	out := new(SynapseWorkerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SynapseWorkerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseWorkerListener) DeepCopyInto(out *SynapseWorkerListener) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]SynapseWorkerResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseWorkerListener.
func (in *SynapseWorkerListener) DeepCopy() *SynapseWorkerListener {
	if in == nil {
		return nil
	}
	out := new(SynapseWorkerListener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseWorkerResource) DeepCopyInto(out *SynapseWorkerResource) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseWorkerResource.
func (in *SynapseWorkerResource) DeepCopy() *SynapseWorkerResource {
	if in == nil {
		return nil
	}
	out := new(SynapseWorkerResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseWorkerSpec) DeepCopyInto(out *SynapseWorkerSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]SynapseWorkerResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseWorkerSpec.
func (in *SynapseWorkerSpec) DeepCopy() *SynapseWorkerSpec {
	if in == nil {
		return nil
	}
	out := new(SynapseWorkerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseWorkerStatus) DeepCopyInto(out *SynapseWorkerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseWorkerStatus.
func (in *SynapseWorkerStatus) DeepCopy() *SynapseWorkerStatus {
	if in == nil {
		return nil
	}
	out := new(SynapseWorkerStatus)
	in.DeepCopyInto(out)
	return out
}
